openapi: 3.0.0
info:
  title: Resume Customization API
  version: 1.0.0
paths:
  /upload_resume:
    post:
      summary: Upload a resume
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                resume:
                  type: string
                  format: binary
      responses:
        '200':
          description: Resume uploaded successfully
  /upload_job_description:
    post:
      summary: Upload a job offer listing
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                job_description:
                  type: string
                  format: binary
      responses:
        '200':
          description: Job offer listing uploaded successfully
  /gather_company_info:
    get:
      summary: Gather information about a company
      parameters:
      - name: company_name
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Company information retrieved
  /summarize_job_description:
    get:
      summary: Summarize a job offer listing
      parameters:
      - name: job_description_id
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Job offer listing summarized
  /classify_company_tone:
    get:
      summary: Classify the company's tone for deciding which prompt version to use
      parameters:
      - name: text
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Tone classified
